## brainfuck in Julia
An exercise in string parsing and esoteric languages. References:
* https://en.wikipedia.org/wiki/Brainfuck
* https://learnxinyminutes.com/docs/bf/

In [50]:
bfcode = ",>,< [ > [ >+ >+ << -] >> [- << + >>] <<< -] >>"
# bfcode = "++++++ [ > ++++++++++ < - ] > +++++ ."

",>,< [ > [ >+ >+ << -] >> [- << + >>] <<< -] >>"

In [51]:
bfcode = replace(bfcode, r"[^\+\-\<\>\.\,\[\]]" => s"") # Eliminating all extranious characters in the code

",>,<[>[>+>+<<-]>>[-<<+>>]<<<-]>>"

Initial processing: identifying pairs of \[ and \], and populating two arrays with indexes (positions of the brackets in the bf code)

In [52]:
indexopen = [] # Array of the left sqare bracket positions

0-element Array{Any,1}

In [53]:
indexclose = [] # Array of the matching right square bracket positions

0-element Array{Any,1}

In [54]:
brstack = [] # Stack for matching bracket positions

0-element Array{Any,1}

In [55]:
n = length(bfcode)

for i=1:n
    if bfcode[i] == '['
        append!(indexopen,i)
        append!(indexclose,0)
        push!(brstack,length(indexopen))
        # println(stderr,"[ ", i, " ", length(indexo))
    elseif bfcode[i] == ']'
        j = pop!(brstack)
        indexclose[j] = i
        # println(stderr,"]", i, length(brstack))
    end
end


In [56]:
[indexopen indexclose]

3×2 Array{Int64,2}:
  5  30
  7  15
 18  25

In [57]:
# Verify matching [ and ]

if length(brstack) != 0 # Should begin and end with empty call stack
    error("Mismatching number of [ and ]")
end

In [60]:
cells = Array{UInt8,1}
cells = [0 for i=1:30000] # 30000 from the classic implementation
ptr = 1 # Pointer to the current position in the code
cellno = 1 # Current cell number

1

**Main loop**

In [62]:
while ptr<=n
    global cellno
    cmd = bfcode[ptr]
    if cmd=='+'
        cells[cellno] = cells[cellno]+1
    elseif cmd=='-'
        cells[cellno] = cells[cellno]-1
    elseif cmd=='>'
        cellno = cellno+1
    elseif cmd=='<'
        cellno = cellno-1
    elseif cmd=='.'
        print(Char(cells[cellno]))
    elseif cmd==','
        in = readline()
        cells[cellno] = tryparse(UInt8,in) # nullable parser of the input string; can use error handling here - expect number! 
    elseif cmd=='['
        if cells[cellno]==0
            ptr = indexclose[findfirst(isequal(ptr),indexopen)]
        end
    elseif cmd==']'
        if cells[cellno]!=0
            ptr = indexopen[findfirst(isequal(ptr),indexclose)]
        end
    end
    @debug "Executed $cmd at $ptr. Current cell # $(cellno)\t$(cells[cellno])"
    ptr = ptr+1
end


stdin> 2
stdin> 3


In [63]:
cells[cellno]

6